---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    provider: fabric8
    project: camel-ex421
    version: 0.0.1-SNAPSHOT
    group: org.springboot
  name: camel-ex421
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    project: camel-ex421
    provider: fabric8
    group: org.springboot
