---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 7f80caf2b769155a61c403b667695ca86d8d0c40
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    provider: fabric8
    project: camel-ex421
    version: 0.0.1-SNAPSHOT
    group: org.springboot
  name: camel-ex421
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    project: camel-ex421
    provider: fabric8
    group: org.springboot
