---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      expose: "true"
      provider: fabric8
      project: camel-ex421
      version: 0.0.1-SNAPSHOT
      group: org.springboot
    name: camel-ex421
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      project: camel-ex421
      provider: fabric8
      group: org.springboot
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=camel-ex421&var-version=0.0.1-SNAPSHOT
    labels:
      provider: fabric8
      project: camel-ex421
      version: 0.0.1-SNAPSHOT
      group: org.springboot
    name: camel-ex421
  spec:
    replicas: 1
    selector:
      project: camel-ex421
      provider: fabric8
      group: org.springboot
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=camel-ex421&var-version=0.0.1-SNAPSHOT
        labels:
          provider: fabric8
          project: camel-ex421
          version: 0.0.1-SNAPSHOT
          group: org.springboot
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: springboot/camel-ex421:snapshot-200110-121612-0786
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
